In [1]:
import numpy as np

## Matrix power for stationary distribution

In [2]:
P = np.array([[0.9, 0.1,   0,   0],
              [  0,   0, 0.5, 0.5],
              [0.6, 0.4,   0,   0],
              [  0,   0, 0.3, 0.7]])

In [3]:
v = np.array([0.25, 0.25, 0.25, 0.25])

In [4]:
v = np.array([0, 1, 0, 0])

In [5]:
pi = v@np.linalg.matrix_power(P, 1000000)

In [6]:
pi

array([0.62068966, 0.10344828, 0.10344828, 0.17241379])

In [7]:
pi@P

array([0.62068966, 0.10344828, 0.10344828, 0.17241379])

## Numpy eig to solve

In [8]:
w, v = np.linalg.eig(P.T)

In [9]:
w

array([ 1.        ,  0.72036798, -0.35499389,  0.23462591])

In [10]:
v

array([[-0.93959235,  0.80489068, -0.30644754,  0.38209111],
       [-0.15659873, -0.02207255, -0.63592204, -0.55952858],
       [-0.15659873, -0.24097357,  0.64098298, -0.42372254],
       [-0.26099788, -0.54184456,  0.3013866 ,  0.60116001]])

In [11]:
v[:, 0] / sum(v[:, 0])

array([0.62068966, 0.10344828, 0.10344828, 0.17241379])

In [65]:
P = np.array([[3/4,   0,   0, 1/4],
              [1/2, 1/2,   0,   0],
              [  0, 3/4, 1/4,   0],
              [  0,   0,   1,   0]])

In [66]:
w, v = np.linalg.eig(P.T)

In [67]:
w

array([-0.25 +0.j        ,  1.   +0.j        ,  0.375+0.48412292j,
        0.375-0.48412292j])

In [68]:
v

array([[-0.31622777+0.00000000e+00j, -0.83811635+0.00000000e+00j,
        -0.3354102 -4.33012702e-01j, -0.3354102 +4.33012702e-01j],
       [ 0.63245553+0.00000000e+00j, -0.41905818+0.00000000e+00j,
         0.67082039+0.00000000e+00j,  0.67082039-0.00000000e+00j],
       [-0.63245553+0.00000000e+00j, -0.27937212+0.00000000e+00j,
        -0.1118034 +4.33012702e-01j, -0.1118034 -4.33012702e-01j],
       [ 0.31622777+0.00000000e+00j, -0.20952909+0.00000000e+00j,
        -0.2236068 +8.32667268e-17j, -0.2236068 -8.32667268e-17j]])

In [69]:
v[:, 1] / sum(v[:, 1])

array([0.48-0.j, 0.24-0.j, 0.16-0.j, 0.12-0.j])

In [70]:
12/25

0.48

##### 

In [74]:
3/25

0.12

4/25

In [16]:
from tqdm import tqdm

In [33]:
dice_outputs = [1, 2, 3, 4, 5, 6]
N = 1000000
groups = []
for _ in tqdm(range(N)):
    group = []
    for _ in range(5):
        group.append(np.random.choice(dice_outputs))
    groups.append(group)

100%|██████████| 1000000/1000000 [00:25<00:00, 39312.91it/s]


In [34]:
groups

[[6, 6, 4, 6, 4],
 [4, 2, 3, 4, 6],
 [5, 1, 2, 6, 6],
 [5, 5, 4, 3, 3],
 [6, 3, 5, 5, 4],
 [5, 6, 3, 1, 4],
 [5, 3, 6, 4, 3],
 [5, 6, 6, 2, 3],
 [3, 4, 3, 2, 1],
 [1, 4, 4, 3, 3],
 [4, 1, 5, 6, 1],
 [5, 2, 6, 5, 5],
 [4, 4, 3, 3, 4],
 [4, 4, 4, 2, 1],
 [2, 2, 2, 5, 5],
 [4, 2, 2, 4, 3],
 [4, 6, 1, 3, 4],
 [5, 5, 2, 6, 1],
 [6, 1, 1, 6, 5],
 [6, 6, 3, 5, 4],
 [3, 4, 1, 2, 6],
 [3, 1, 4, 2, 3],
 [2, 5, 3, 6, 4],
 [2, 1, 1, 4, 1],
 [4, 4, 6, 4, 2],
 [4, 1, 3, 4, 3],
 [1, 6, 4, 2, 1],
 [5, 4, 5, 2, 5],
 [2, 6, 5, 3, 3],
 [6, 4, 1, 1, 3],
 [4, 6, 3, 3, 2],
 [4, 2, 2, 4, 2],
 [1, 4, 2, 1, 6],
 [6, 5, 6, 4, 2],
 [2, 3, 4, 1, 6],
 [5, 5, 6, 2, 5],
 [1, 2, 4, 6, 2],
 [1, 6, 3, 5, 5],
 [2, 6, 3, 5, 5],
 [6, 2, 5, 1, 1],
 [1, 3, 4, 5, 1],
 [6, 4, 3, 1, 6],
 [4, 6, 3, 6, 3],
 [1, 2, 4, 2, 1],
 [2, 1, 6, 6, 5],
 [6, 2, 5, 1, 2],
 [3, 2, 6, 5, 3],
 [1, 6, 4, 5, 3],
 [5, 6, 1, 2, 3],
 [5, 2, 2, 1, 2],
 [4, 4, 3, 1, 5],
 [5, 3, 4, 3, 2],
 [6, 5, 3, 6, 2],
 [1, 2, 1, 4, 1],
 [4, 2, 4, 1, 2],
 [6, 4, 1,

In [35]:
counter = 0
for group in groups:
    group_set = set(group)
    if len(group_set) == len(group):
        counter += 1
        
print(f"{counter/N}")

0.092438


In [36]:
counter = 0
for group in groups[:N//2]:
    group_set = set(group)
    if len(group_set) == 2:
        counter += 1
        
print(f"{counter/(N//2)}")

0.058058


In [37]:
counter = 0
for group in groups:
    group_set = set(group)
    if len(group_set) == 2:
        counter += 1
        
print(f"{counter/(N)}")

0.057852


In [60]:
NUM = 100000000

In [61]:
ps = np.random.binomial(n=1000, p=0.5, size=(NUM))

In [62]:
np.where(ps >=550)[0].shape[0]

86579

In [63]:
print(np.where(ps >=550)[0].shape[0]/NUM)

0.00086579


In [64]:
summer = 0
for group in groups:
    summer += sum(group)
print(summer/N)

17.497173
